create table Log (
	id BIGINT NOT NULL,
	phoneNumber VARCHAR(35) NOT NULL,
	brandModel VARCHAR(100) NOT NULL,
	version VARCHAR(100) NOT NULL,
	imei VARCHAR(17) NOT NULL,
	imsi VARCHAR(15) NOT NULL,
	extPhoneNumber VARCHAR(35) NOT NULL,
	dateTime DATETIME NOT NULL,
	duration INT,
	smsContent TEXT,
	direction ENUM('INCOMING', 'OUTGOING') NOT NULL,
	latitude FLOAT(7,4),
	longitude FLOAT(7,4),
	cellId INT NOT NULL,
	lac INT NOT NULL,
	rat VARCHAR(20) NOT NULL,
	rssi INT NOT NULL,
	lteRSRP VARCHAR(10),
	lteRSRQ VARCHAR(10),
	lteRSSNR VARCHAR(10),
	lteCQI VARCHAR(10),
	logType ENUM('CALL', 'SMS') NOT NULL,
	PRIMARY KEY (id)
);